version: 1.0.{build}

branches:
  only:
  - master

before_build:
- ps: nuget restore VoteSystem.sln

build:
  project: VoteSystem.sln
  verbosity: minimal

notifications:
- provider: Email
  to:
  - todorov.h@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: wa33m2iJHeV7W/T71bNBvA+Lh0cHuRbYTgVBWyEvCR3AIdV0mO78jI7WmRpDeyiX 

after_test: 
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single  test\VoteSystem.Services.Web.Tests\bin\Debug\VoteSystem.Services.Web.Tests.dll 
    test\VoteSystem.Web.Controllers.Tests\bin\Debug\VoteSystem.Web.Controllers.Tests.dll" -output:coverage.xml

  - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml